### ISSUE TITLE
Conda support

### ISSUE THREAD

**Issue by davidandreoletti** [dwt/pyexpect#1]
Hi,

Thanks for the lib :-)

Would you consider releasing pyexpect on Conda-forge ?

**Comment by dwt** [comment]
Nothing against it - what is required to release something there? I was hoping that pure python libraries like pyexpect can be installed in conda without special preparations - but I have never used conda myself.

**Comment by dwt** [comment]
This seems to suggest this should be possible, could you elaborate on what other preparations are required from pyexpect?

**Comment by dwt** [comment]
This https://jordanbenge.medium.com/how-to-install-pip-packages-in-an-anaconda-conda-env-a839ef660b03 seems to be an even better explanation on how to do it.

**Comment by davidandreoletti** [comment]
Conda has recently added explicit support for pypi￼ packages.

So this ticket is moot now.

Thanks for the prompt response.
